### ISSUE TITLE
Mapping for PermitMod

### ISSUE THREAD

**Issue by CanDKD** [agrc/uic-forms#12]
https://github.com/agrc/uic-forms/blob/f6d1f631399ffe09e92b9b82a2924eca692c45d5/uic-forms/services/Querier.cs#L40-L90

I am not sure if this is where the code counts the number of PermitDeterminations (7520-1 Part VI) but pdf form field VIE_1, 3, 4, 5 should be mapped to the new PermitMod column (P or 16) of the .csv.  The coded value for AuthorizationAction for Permit Modifications Approved is 'PM'

**Comment by steveoh** [comment]
I believe this is the code for the vie from the pdf. I will map it to the PermitMod

https://github.com/agrc/uic-forms/blob/master/uic-forms/Program.cs#L93-L98

**Comment by CanDKD** [comment]
> I believe this is the code for the vie from the pdf. I will map it to the PermitMod
> 
> https://github.com/agrc/uic-forms/blob/master/uic-forms/Program.cs#L93-L98

Yes, you are correct.  I was looking in the Querier instead of the Program
