### ISSUE TITLE
Quarterly RTC Wells

### ISSUE THREAD

**Issue by CanDKD** [agrc/uic-forms#13]
https://github.com/agrc/uic-forms/blob/ed32df24d4573e3a24372234a2abf48c49d9c836/uic-forms/Program.cs#L222-L226

We will not be using the above bit of code for the .csv fields WellRTC and WellRTC_SNC.  We will only be reporting cumulative data for these fields using the following code which you currently have commented out:

https://github.com/agrc/uic-forms/blob/master/uic-forms/Program.cs#L228-L232

**Comment by steveoh** [comment]
ok so replace viia with viib. got it.
