### ISSUE TITLE
Improving readability of .log.txt file

### ISSUE THREAD

**Issue by CanDKD** [agrc/uic-forms#14]
https://github.com/agrc/uic-forms/blob/5372488e6970c17a736cd2492965e3cb3ff58026/uic-forms/models/CsvMappings.cs#L17

Would it be a huge headache to write the csv column name to the .log.txt file rather than the old pdf form field names?  This would facilitate the writing of the narrative that accompanies the csv submittals.  Thanks.

**Comment by steveoh** [comment]
Not a huge headache. Just a lot of typing. I'll get it done for ya.

**Comment by CanDKD** [comment]
Thanks, Steve.

*Candace C. Cady, PG | Underground Injection Control (UIC) Program*
phone:  801.536.4352

office location:    195 North 1950 West, Salt Lake City, Utah  84116
mailing address:  Utah Division of Water Quality
                          PO Box 144870
                          Salt Lake City, Utah   84114

*Emails to and from this email address may be considered public records and
thus subject to Utah GRAMA requirements.*
