### ISSUE TITLE
Inventory for some Wells should be blank not 0

### ISSUE THREAD

**Issue by CanDKD** [agrc/uic-forms#16]
Applies to ClassIID ClassIIR ClassIIOther and ClassVI

https://github.com/agrc/uic-forms/blob/8f5f6f35bc0aa695cee052a6f3e358ec31f3f5a7/uic-forms/services/Querier.cs#L959-L1060

I just made a test submission to the web service.  Inventory failed because DEQ doesn't have authority over Class II and VI wells.  We entered '0' in those fields, the application wants to see blanks.  Other than this little glitch.  We're good!!

**Comment by steveoh** [comment]
do you mean these ones...

https://github.com/agrc/uic-forms/blob/master/uic-forms/models/CsvMappings.cs#L169-L177

**Comment by CanDKD** [comment]
Those are the ones.  I didn't scroll down far enough in the Csv Mapping
code.  So ClassIID, ClassIIR, Class IIOther, and ClassVIWells should be
blank not '0'

*Candace C. Cady, PG | Underground Injection Control (UIC) Program*
phone:  801.536.4352

office location:    195 North 1950 West, Salt Lake City, Utah  84116
mailing address:  Utah Division of Water Quality
                          PO Box 144870
                          Salt Lake City, Utah   84114

*Emails to and from this email address may be considered public records and
thus subject to Utah GRAMA requirements.*
