### ISSUE TITLE
Quarterly submittals do not require all forms

### ISSUE THREAD

**Issue by steveoh** [agrc/uic-forms#17]
From @candkd

> we will be required to submit quarterly, but that each quarter will require submittal of different forms.  
> 1st Qtr (Oct - Dec) - 7520-4 only; 
> 2nd Qtr (Jan - March) - 7520-1 thru 7520-4,  BiAnnual Narrative (uic-forms tool doesn't apply); 
> 3rd Qtr (April - June) - 7520-4 only; 
> 4th Qtr - 7520-1 thru 7520-4, inventory, Annual Narrative (uic-forms tool doesn't apply)

For now they will remove the extra forms, but in the future we should look into making the tool smarter.

**Comment by CanDKD** [comment]
Steve, let's delete this issue because  I decide once I am in the EPA's UIC Data Application which 7520 form to submit.  We import the csv's then I decide which form to submit based on the reporting quarter.
