### ISSUE TITLE
Add 4 New Columns

### ISSUE THREAD

**Issue by CanDKD** [agrc/uic-forms#8]
Add another field after:
-- https://github.com/agrc/uic-forms/blob/master/uic-forms/models/CsvMappings.cs#L23 (PermitDenied)
for 'PermitMod'
-- https://github.com/agrc/uic-forms/blob/master/uic-forms/models/CsvMappings.cs#L96 (OtherLeakEval_Fail)
for 'OtherLeakEval_Spec'
-- https://github.com/agrc/uic-forms/blob/master/uic-forms/models/CsvMappings.cs#L104 (OtherFluidTest_Fail)
for 'OtherFluidTest_Spec'
-- https://github.com/agrc/uic-forms/blob/master/uic-forms/models/CsvMappings.cs#L109 (Remedial_Other)
for 'RemedialOther_Spec'

**Comment by steveoh** [comment]
Should these all default to 0 or empty string?
